"""Change Item.name to String(250)

Revision ID: 1cd1c1517f1
Revises: 512fc62e87fe
Create Date: 2013-01-30 01:59:56.375586

"""

# revision identifiers, used by Alembic.
revision = '1cd1c1517f1'
down_revision = '512fc62e87fe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
