"""Added last_updated to player model

Revision ID: 219a7f3219b8
Revises: 5a26ff150301
Create Date: 2013-02-13 18:03:28.333566

"""

# revision identifiers, used by Alembic.
revision = '219a7f3219b8'
down_revision = '5a26ff150301'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'last_updated')
    ### end Alembic commands ###
