"""Added update error flag to player

Revision ID: 2bf289a18362
Revises: 4ac3e2230f21
Create Date: 2013-01-31 04:33:34.471654

"""

# revision identifiers, used by Alembic.
revision = '2bf289a18362'
down_revision = '4ac3e2230f21'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('profile_update_error', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'profile_update_error')
    ### end Alembic commands ###
