"""Added match detail fields

Revision ID: 2f5f82e2bb08
Revises: 2bf289a18362
Create Date: 2013-01-31 05:21:47.321655

"""

# revision identifiers, used by Alembic.
revision = '2f5f82e2bb08'
down_revision = '2bf289a18362'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('tower_status_dire', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('barracks_status_dire', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('positive_votes', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('league_id', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('barracks_status_radiant', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('cluster', sa.String(length=250), nullable=True))
    op.add_column('match', sa.Column('num_human_player', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('replay_salt', sa.String(length=250), nullable=True))
    op.add_column('match', sa.Column('first_blood_time', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('negative_votes', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('tower_status_radiant', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('radiant_win', sa.Boolean(), nullable=True))
    op.add_column('player_match', sa.Column('item_slot_2', sa.Integer(), nullable=True))
    op.add_column('player_match', sa.Column('item_slot_3', sa.Integer(), nullable=True))
    op.add_column('player_match', sa.Column('item_slot_0', sa.Integer(), nullable=True))
    op.add_column('player_match', sa.Column('xp_per_min', sa.Integer(), nullable=True))
    op.add_column('player_match', sa.Column('denies', sa.Integer(), nullable=True))
    op.add_column('player_match', sa.Column('gold_spent', sa.Integer(), nullable=True))
    op.add_column('player_match', sa.Column('gold', sa.Integer(), nullable=True))
    op.add_column('player_match', sa.Column('deaths', sa.Integer(), nullable=True))
    op.add_column('player_match', sa.Column('item_slot_5', sa.Integer(), nullable=True))
    op.add_column('player_match', sa.Column('gold_per_min', sa.Integer(), nullable=True))
    op.add_column('player_match', sa.Column('item_slot_4', sa.Integer(), nullable=True))
    op.add_column('player_match', sa.Column('kills', sa.Integer(), nullable=True))
    op.add_column('player_match', sa.Column('item_slot_1', sa.Integer(), nullable=True))
    op.add_column('player_match', sa.Column('hero_damage', sa.Integer(), nullable=True))
    op.add_column('player_match', sa.Column('assists', sa.Integer(), nullable=True))
    op.add_column('player_match', sa.Column('last_hits', sa.Integer(), nullable=True))
    op.add_column('player_match', sa.Column('hero_healing', sa.Integer(), nullable=True))
    op.add_column('player_match', sa.Column('tower_damage', sa.Integer(), nullable=True))
    op.add_column('player_match', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('player_match', sa.Column('abandoned', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_match', 'abandoned')
    op.drop_column('player_match', 'level')
    op.drop_column('player_match', 'tower_damage')
    op.drop_column('player_match', 'hero_healing')
    op.drop_column('player_match', 'last_hits')
    op.drop_column('player_match', 'assists')
    op.drop_column('player_match', 'hero_damage')
    op.drop_column('player_match', 'item_slot_1')
    op.drop_column('player_match', 'kills')
    op.drop_column('player_match', 'item_slot_4')
    op.drop_column('player_match', 'gold_per_min')
    op.drop_column('player_match', 'item_slot_5')
    op.drop_column('player_match', 'deaths')
    op.drop_column('player_match', 'gold')
    op.drop_column('player_match', 'gold_spent')
    op.drop_column('player_match', 'denies')
    op.drop_column('player_match', 'xp_per_min')
    op.drop_column('player_match', 'item_slot_0')
    op.drop_column('player_match', 'item_slot_3')
    op.drop_column('player_match', 'item_slot_2')
    op.drop_column('match', 'radiant_win')
    op.drop_column('match', 'tower_status_radiant')
    op.drop_column('match', 'negative_votes')
    op.drop_column('match', 'first_blood_time')
    op.drop_column('match', 'replay_salt')
    op.drop_column('match', 'num_human_player')
    op.drop_column('match', 'cluster')
    op.drop_column('match', 'barracks_status_radiant')
    op.drop_column('match', 'duration')
    op.drop_column('match', 'league_id')
    op.drop_column('match', 'positive_votes')
    op.drop_column('match', 'barracks_status_dire')
    op.drop_column('match', 'tower_status_dire')
    ### end Alembic commands ###
