"""Added players and matches

Revision ID: 4ac3e2230f21
Revises: 4bf8df862b49
Create Date: 2013-01-30 07:29:29.514723

"""

# revision identifiers, used by Alembic.
revision = '4ac3e2230f21'
down_revision = '4bf8df862b49'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lobby_type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_match',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.Column('match_id', sa.BigInteger(), nullable=True),
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.Column('is_dire', sa.Boolean(), nullable=True),
    sa.Column('slot', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hero_id'], ['hero.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_match')
    op.drop_table('match')
    op.drop_table('player')
    ### end Alembic commands ###
