"""Added Hero model

Revision ID: 4bf8df862b49
Revises: 1cd1c1517f1
Create Date: 2013-01-30 02:01:37.216117

"""

# revision identifiers, used by Alembic.
revision = '4bf8df862b49'
down_revision = '1cd1c1517f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('proper_name', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('proper_name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hero')
    ### end Alembic commands ###
