"""Added Item model

Revision ID: 512fc62e87fe
Revises: 29678636b608
Create Date: 2013-01-30 00:47:57.486978

"""

# revision identifiers, used by Alembic.
revision = '512fc62e87fe'
down_revision = '29678636b608'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table(u'models')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'models',
    sa.Column(u'id', sa.INTEGER(), server_default="nextval('models_id_seq'::regclass)", nullable=False),
    sa.Column(u'name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column(u'value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'id', name=u'models_pkey')
    )
    op.drop_table('item')
    ### end Alembic commands ###
