"""Added is_registered column to player

Revision ID: 5a26ff150301
Revises: 5704cbb75778
Create Date: 2013-02-13 17:40:09.108699

"""

# revision identifiers, used by Alembic.
revision = '5a26ff150301'
down_revision = '5704cbb75778'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('is_registerd', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'is_registerd')
    ### end Alembic commands ###
